# Generated by Django 4.0.1 on 2022-01-12 02:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='item',
            old_name='descriptiom',
            new_name='description',
        ),
    ]
