# Generated by Django 4.0.1 on 2022-01-15 20:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0002_rename_descriptiom_item_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='inventory',
            field=models.IntegerField(default=0),
        ),
    ]
