# Generated by Django 4.0.1 on 2022-01-19 02:15

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0007_alter_item_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='warehouseinventory',
            name='stock',
            field=models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)]),
        ),
    ]
