# Generated by Django 4.0.1 on 2022-01-19 03:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0010_alter_item_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='price',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='warehouseinventory',
            name='stock',
            field=models.PositiveBigIntegerField(default=0),
        ),
    ]
