# Generated by Django 4.0.1 on 2022-01-20 02:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0012_alter_item_description_alter_item_name_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Item',
            new_name='Product',
        ),
        migrations.RenameField(
            model_name='warehouseinventory',
            old_name='item',
            new_name='product',
        ),
    ]
